[build]
  base    = "docs"
  publish = "public"
  command = "gatsby build --prefix-paths && mkdir -p docs/apollo-server && mv public/* docs/apollo-server && mv docs public/ && mv public/docs/apollo-server/_redirects public"
[build.environment]
  NPM_VERSION = "6"
