title: Apollo Server
propertytitle: Using Apollo Server
subtitle: Apollo Server
description: A guide to using Apollo Server.
version: 2
versions:
  - '1'
  - '2'
sidebar_categories:
  null:
    - index
    - getting-started
    - whats-new
  Essentials:
    - essentials/schema
    - essentials/server
    - essentials/data
  Features:
    - features/mocking
    - features/errors
    - features/apq
    - features/data-sources
    - features/cdn
    - features/subscriptions
    - features/file-uploads
    - features/metrics
    - features/scalars-enums
    - features/unions-interfaces
    - features/directives
    - features/creating-directives
  # Schema stitching:
  #   - features/schema-stitching
  #   - features/remote-schemas
  #   - features/schema-delegation
  #   - features/schema-transforms
  Deployment:
    # - deployment/index
    - deployment/heroku
    - deployment/lambda
    - deployment/now
  API Reference:
    - api/apollo-server
    - title: graphql-subscriptions
      href: https://www.apollographql.com/docs/graphql-subscriptions
    - api/graphql-tools
  Migration:
    - migration-two-dot
    - migration-engine

github_repo: apollographql/apollo-server
content_root: docs/source

typescript_api_box:
  data_file: docs.json

url: https://www.apollographql.com/docs/apollo-server/
root: /docs/apollo-server/

public_dir: public/docs/apollo-server

versioned-netlify-redirects:
  netlify_site_id: apollo-server-docs
