title: Apollo Server
propertytitle: Using Apollo Server
subtitle: Apollo Server
description: A guide to using Apollo Server.
versions:
  - '1'
sidebar_categories:
  null:
    - index
    - why-apollo
    - getting-started
    - whats-new
  Essentials:
    - essentials/building-schema
    - essentials/running-a-server
    - essentials/fetching-data
  Schema Development:
    - schemas/organization
    - schemas/types
    - schemas/directives
    - schemas/resolvers
    - schemas/context
  Best Practices:
    - best-practices/authentication
    - best-practices/permissions
    - best-practices/schema-design
    - best-practices/performance
    - best-practices/security
    - best-practices/caching
    - best-practices/monitoring
    - best-practices/versioning
    - best-practices/infrastructure
    - best-practices/testing
    - best-practices/secrets
  Working with Backends:
    - backends/general
    - backends/sql
    - backends/mongodb
    - backends/rest
    - backends/prisma
  Deploy Apollo Server:
    - deploy/best-practices
    - deploy/heroku
  Advanced:
    - advanced/query-mechanics
  API Reference:
    - api/apollo-server
    - api/graphql-subscriptions
    - api/apollo-engine

github_repo: apollographql/apollo-server
content_root: docs/source

typescript_api_box:
  data_file: docs.json

url: https://www.apollographql.com/docs/apollo-server/
root: /docs/apollo-server/

public_dir: public/docs/apollo-server
